export const LOAD_PRACTICES_SUCCESS = "LOAD_PRACTICES_SUCCESS";
export const LOAD_CONSULTANTS_SUCCESS = "LOAD_CONSULTANTS_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const DELETE_PRACTICE_OPTIMISTIC = "DELETE_PRACTICE_OPTIMISTIC";
export const DELETE_CONSULTANT_OPTIMISTIC = "DELETE_CONSULTANT_OPTIMISTIC";
